CREATE TABLE SHOULDBEINFOTABLE (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
    shouldbe TEXT NOT NULL,
    lat INTEGER NOT NULL,
    long INTEGER NOT NULL
);

CREATE TABLE LIKETABLE (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	fk_shouldbe_id,
	FOREIGN KEY (fk_shouldbe_id) REFERENCES SHOULDBEINFOTABLE
);
